# Default Config.yml! -chieloos
ver: 0.1a
disabled: false
use-wg-region: true
wg-region-id: wts
commands:
  search:
    command-name: search
    help-message: Searches for trade IDs by item or player.
  buy:
    command-name: buy
    help-message: Buys the amount of items from a trader.
  order:
    command-name: order
    help-message: Orders an amount of an item for the price per item.
  confirm:
    command-name: confirm
    help-message: Confirms an action where applicable.
  mailbox:
    command-name: mailbox
    help-message: Lists current mailboxes or opens a player's mailbox.
  sell:
    command-name: sell
    help-message: Sells an amount of an item for the price per item.
  cancel:
    command-name: cancel
    help-message: Cancels a trade by trade ID.
  page:
    command-name: page
    help-message: Changes the page of information where applicable.
  help:
    command-name: help
    help-message: Lists the WookieeTrader command list.
enchants:
  PROTECTION_ENVIRONMENTAL:
    name: Protection
    abbreviation: abv
  PROTECTION_FIRE:
    name: Fire Protection
    abbreviation: abv
  PROTECTION_FALL:
    name: Feather Falling
    abbreviation: abv
  PROTECTION_EXPLOSIONS:
    name: Blast Protection
    abbreviation: abv
  PROTECTION_PROJECTILE:
    name: Projectile Protection
    abbreviation: abv
  OXYGEN:
    name: Respiration
    abbreviation: abv
  WATER_WORKER:
    name: Aqua Affinity
    abbreviation: abv
  THORNS:
    name: Thorns
    abbreviation: abv
  DAMAGE_ALL:
    name: Sharpness
    abbreviation: abv
  DAMAGE_UNDEAD:
    name: Smite
    abbreviation: abv
  DAMAGE_ARTHROPODS:
    name: Bane of Arthropods
    abbreviation: abv
  KNOCKBACK:
    name: Knockback
    abbreviation: abv
  FIRE_ASPECT:
    name: Fire Aspect
    abbreviation: abv
  LOOT_BONUS_MOBS:
    name: Looting
    abbreviation: abv
  DIG_SPEED:
    name: Effeciency
    abbreviation: abv
  SILK_TOUCH:
    name: Silk Touch
    abbreviation: abv
  DURABILITY:
    name: Unbreaking
    abbreviation: abv
  LOOT_BONUS_BLOCKS:
    name: Fortune
    abbreviation: abv
  ARROW_DAMAGE:
    name: Power
    abbreviation: abv
  ARROW_KNOCKBACK:
    name: Punch
    abbreviation: abv
  ARROW_FIRE:
    name: Flame
    abbreviation: abv
  ARROW_INFINITE:
    name: Infinity
    abbreviation: abv